# Lab 02: Manipulate PyTorch Tensors -- exercise

In [1]:
import torch

### Make the matrices A and B below. Add them together to obtain a matrix C. Print these three matrices.
$$
A =\begin{bmatrix}
1 & 2 \\ 3 & 4
\end{bmatrix}  
\qquad 
B =\begin{bmatrix}
10 & 20 \\ 30 & 40
\end{bmatrix}  \qquad C=A+B =?
$$

In [2]:
# write your code here
A = torch.Tensor([[1, 2], [3, 4]])
B = torch.Tensor([[10, 20], [30, 40]])
C = A + B

print(C)

tensor([[11., 22.],
        [33., 44.]])


### Print the dimension, size and type of the matrix A. Remember, the commands are dim(), size() and type()

In [3]:
# write your code here
print(A.dim())
print(A.size())
print(A.type())

2
torch.Size([2, 2])
torch.FloatTensor


### Convert the matrix A to be an integer matrix  (type LongTensor). Remember, the command is long(). Then print the type to check it was indeed converted.

In [4]:
# write your code here
A = A.long()
print(A.type())

torch.LongTensor


### Make a random 5 x 2 x 3 Tensor. The command is torch.rand.  Then do the following:   1) Print the tensor,  2) Print its type, 3) Print its dimension,  4) Print its size, 5) Print the size of its middle dimension.

In [5]:
# write your code here
random_tensor = torch.rand((5, 2, 3))
print(random_tensor)
print(random_tensor.type())
print(random_tensor.dim())
print(random_tensor.size())
print(random_tensor.size(1))

tensor([[[0.9957, 0.4671, 0.9274],
         [0.9264, 0.1422, 0.2127]],

        [[0.3911, 0.4103, 0.4741],
         [0.8376, 0.8893, 0.3240]],

        [[0.7933, 0.7735, 0.1013],
         [0.9668, 0.6486, 0.2655]],

        [[0.6483, 0.1261, 0.8561],
         [0.1766, 0.0699, 0.7094]],

        [[0.8988, 0.0203, 0.1771],
         [0.3806, 0.5936, 0.6382]]])
torch.FloatTensor
3
torch.Size([5, 2, 3])
2


### Make 2 x 3 x 4 x 5 tensor filled with zeros then print it. (The command is torch.zeros). See if you can make sense of the display.

In [6]:
# write your code here
zeros_tensor = torch.zeros((2, 3, 4, 5))
print(zeros_tensor)


tensor([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]])
