# Lab 02: Manipulate PyTorch Tensors -- exercise

In [2]:
import torch

### Make the matrices A and B below. Add them together to obtain a matrix C. Print these three matrices.
$$
A =\begin{bmatrix}
1 & 2 \\ 3 & 4
\end{bmatrix}  
\qquad 
B =\begin{bmatrix}
10 & 20 \\ 30 & 40
\end{bmatrix}  \qquad C=A+B =?
$$

In [5]:
# write your code here
A = torch.Tensor([[1, 2], [3, 4]])
B = torch.Tensor([[10, 20], [30, 40]])
C = A + B

print(C)

tensor([[11., 22.],
        [33., 44.]])


### Print the dimension, size and type of the matrix A. Remember, the commands are dim(), size() and type()

In [6]:
# write your code here
print(A.dim())
print(A.size())
print(A.type())

2
torch.Size([2, 2])
torch.FloatTensor


### Convert the matrix A to be an integer matrix  (type LongTensor). Remember, the command is long(). Then print the type to check it was indeed converted.

In [8]:
# write your code here
A = A.long()
print(A.type())

torch.LongTensor


### Make a random 5 x 2 x 3 Tensor. The command is torch.rand.  Then do the following:   1) Print the tensor,  2) Print its type, 3) Print its dimension,  4) Print its size, 5) Print the size of its middle dimension.

In [10]:
# write your code here
random_tensor = torch.rand((5, 2, 3))
print(random_tensor)
print(random_tensor.type())
print(random_tensor.dim())
print(random_tensor.size())
print(random_tensor.size(1))

tensor([[[0.3211, 0.2727, 0.1112],
         [0.9812, 0.8726, 0.6740]],

        [[0.5508, 0.0179, 0.8773],
         [0.0245, 0.5457, 0.8359]],

        [[0.3394, 0.9773, 0.9929],
         [0.8658, 0.4624, 0.0998]],

        [[0.3322, 0.4290, 0.0477],
         [0.5168, 0.1494, 0.4568]],

        [[0.6521, 0.1027, 0.3606],
         [0.1223, 0.9220, 0.1925]]])
torch.FloatTensor
3
torch.Size([5, 2, 3])
2


### Make 2 x 3 x 4 x 5 tensor filled with zeros then print it. (The command is torch.zeros). See if you can make sense of the display.

In [11]:
# write your code here
zeros_tensor = torch.zeros((2, 3, 4, 5))
print(zeros_tensor)


tensor([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]])
