# Lab 01 : Linear module -- exercise

# Inspecting a linear module

In [2]:
import torch
import torch.nn as nn

### Make a linear module  WITHOUT bias that takes input of size 2 and return output of size 3. 

In [3]:
mod = nn.Linear(2, 3, bias=False)     # complete here
print(mod)

Linear(in_features=2, out_features=3, bias=False)


### Print the internal parameters of the module. Try to print the bias and double check that it return you "None"

In [4]:
print(mod.weight)  # complete here  )
print(mod.bias)  # complete here  )

Parameter containing:
tensor([[ 0.1248,  0.4239],
        [-0.3611,  0.1030],
        [-0.0761, -0.6555]], requires_grad=True)
None


### Make a vector $x=\begin{bmatrix}1\\1 \end{bmatrix}$ and feed it to your linear module. What is the output?

In [5]:
x = torch.Tensor([1, 1])  # complete here  
print(x)
y = mod(x)  # complete here  
print(y)

tensor([1., 1.])
tensor([ 0.5487, -0.2581, -0.7317], grad_fn=<SqueezeBackward4>)


### Change the internal parameters of your module so that the weights become 
$
W=\begin{bmatrix}
1&2 \\ 3&4 \\ 5&6
\end{bmatrix}
$. You need to write 6 lines, one per entry to be changed.

In [6]:
with torch.no_grad():
    # complete here  
    mod.weight[0, 0] = 1
    # complete here
    mod.weight[0, 1] = 2  
    # complete here
    mod.weight[1, 0] = 3  
    # complete here
    mod.weight[1, 1] = 4  
    # complete here
    mod.weight[2, 0] = 5  
    # complete here
    mod.weight[2, 1] = 6  
    print(mod.weight)

Parameter containing:
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], requires_grad=True)


### Feed the vector x to your module with updated parameters. What is the output? 

In [7]:
y = mod(x) # complete here  
print(y)

tensor([ 3.,  7., 11.], grad_fn=<SqueezeBackward4>)


### Compute by hand $y=Wx$ and check that pytorch got it correctly. 

$$
\begin{bmatrix}
1&2 \\ 3&4 \\ 5&6
\end{bmatrix}
\begin{bmatrix}1\\1 \end{bmatrix}=
\begin{bmatrix}?\\? \\ ? \end{bmatrix}
$$